version: 1.0.{build}
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: Passw0rd
build_script:
- ps: >-
    ./Build.ps1 -Task Default -verbose
artifacts:
- path: .\BuildOutput\FRPSUGModule
  name: FRPSUGModule
