version: 1.0.{build}
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: Passw0rd
install:
- ps: >-
    ./CI/Install.ps1
build_script:
- ps: >-
    ./CI/Clean.ps1

    ./CI/Compile.ps1
test_script:
- ps: ./CI/Tests.ps1
artifacts:
- path: .\FRPSUGModule
  name: FRPSUGModule