version: 1.0.{build}
image: Visual Studio 2017
environment:
  APPVEYOR_RDP_PASSWORD: Passw0rd
build_script:
- ps: >-
    ./Build.ps1 -Tasks Default -verbose
artifacts:
- path: .\<%= $PLASTER_PARAM_ModuleName %>
  name: <%= $PLASTER_PARAM_ModuleName %>